// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Playground.EF;

namespace Playground.Migrations
{
    [DbContext(typeof(PlaygroundDbContext))]
    [Migration("20210810015057_AddWordsPerMinuteFrequencyTable")]
    partial class AddWordsPerMinuteFrequencyTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Playground.Models.Temp", b =>
                {
                    b.Property<int>("TempId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("TempName")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("TempId");

                    b.ToTable("Temp");
                });

            modelBuilder.Entity("Playground.Models.WordsPerMinuteFrequency", b =>
                {
                    b.Property<int>("WordsPerMinute")
                        .HasColumnType("int");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.HasKey("WordsPerMinute");

                    b.ToTable("WordsPerMinuteFrequency");
                });
#pragma warning restore 612, 618
        }
    }
}
